"use client";

import { useCallback, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

// The cross-organisation link path's own parent-facing half -- the
// outbound-code slot the Share sheet used to occupy before it was
// removed this morning for showing a code that went nowhere. This is
// what should have been there: its own kind of code (Decision 1 --
// never the Passport ID shown on /more, which is a plain reference,
// not a credential), single-use, expiring, generated by the parent,
// entered by a school. Mirrors ClientGuardianAndClaimCodeSection.tsx's
// own visual/loading shape deliberately, not reinvented -- same card
// chrome, same generate/outstanding/revoke states, applied to
// generate_institution_link_code()/get_institution_link_code_status()/
// revoke_institution_link_code() (migration 0294) instead of the
// clinic-side claim-code RPCs that component calls.
//
// No reason required to revoke, unlike revoke_passport_claim_code() --
// that RPC revokes access someone ELSE (a family member's own future
// self, or a school) might be relying on, so 0126 gave it an audit
// trail. This is a parent revoking their own not-yet-used code before
// anyone has acted on it; nobody else is affected, and there is
// nothing to record a reason against.

interface LinkCodeStatus {
  id: string;
  code: string;
  expiresAt: string;
}

function daysRemaining(iso: string): number {
  const diffMs = new Date(iso).getTime() - Date.now();
  return Math.max(0, Math.ceil(diffMs / 86_400_000));
}

export function InstitutionLinkCodeSection({ passportId }: { passportId: string }) {
  const [linkCode, setLinkCode] = useState<LinkCodeStatus | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);
  const [isConfirmingRevoke, setIsConfirmingRevoke] = useState(false);
  const [isRevoking, setIsRevoking] = useState(false);
  const [revokeError, setRevokeError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setIsLoading(true);
    const supabase = createClient();
    const { data } = await supabase.rpc("get_institution_link_code_status", { p_passport_id: passportId });
    const row = ((data ?? []) as { id: string; code: string; expires_at: string }[])[0];
    setLinkCode(row ? { id: row.id, code: row.code, expiresAt: row.expires_at } : null);
    setIsLoading(false);
  }, [passportId]);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    load();
  }, [load]);

  async function handleGenerate() {
    setIsGenerating(true);
    setGenerateError(null);
    const supabase = createClient();
    const { error } = await supabase.rpc("generate_institution_link_code", { p_passport_id: passportId });
    setIsGenerating(false);
    if (error) {
      setGenerateError(error.message);
      return;
    }
    load();
  }

  async function handleRevoke() {
    if (!linkCode) return;
    setIsRevoking(true);
    setRevokeError(null);
    const supabase = createClient();
    const { error } = await supabase.rpc("revoke_institution_link_code", { p_link_code_id: linkCode.id });
    setIsRevoking(false);
    if (error) {
      setRevokeError(error.message);
      return;
    }
    setIsConfirmingRevoke(false);
    load();
  }

  if (isLoading) {
    return <div className="mt-3 h-[60px] animate-pulse rounded-xl bg-brand-off-white/50" />;
  }

  if (!linkCode) {
    return (
      <div className="mt-3">
        <button
          type="button"
          onClick={handleGenerate}
          disabled={isGenerating}
          className="w-full rounded-xl border border-brand-prussian-blue px-4 py-2.5 text-center text-sm font-semibold text-brand-prussian-blue disabled:opacity-50"
        >
          {isGenerating ? "Generating…" : "Give This Code To A New School Or Clinic"}
        </button>
        {generateError && (
          <p role="alert" className="mt-2 text-xs font-medium text-brand-golden-brown">
            {generateError}
          </p>
        )}
      </div>
    );
  }

  return (
    <div className="mt-3 rounded-xl bg-brand-off-white/50 p-4">
      <div className="flex items-start justify-between gap-2">
        <p className="text-xs font-semibold uppercase tracking-wide text-brand-neutral-black/50">Link code</p>
        <span className="flex-shrink-0 rounded-full bg-brand-golden-brown/15 px-2.5 py-1 text-xs font-semibold text-brand-golden-brown">
          EXPIRES IN {daysRemaining(linkCode.expiresAt)} DAY{daysRemaining(linkCode.expiresAt) === 1 ? "" : "S"}
        </span>
      </div>
      <p className="mt-1 font-heading text-2xl font-bold tracking-widest text-brand-prussian-blue">
        {linkCode.code}
      </p>
      <p className="mt-1 text-xs text-brand-neutral-black/50">
        Give this to your child&apos;s new school or clinic. They&apos;ll connect their own record -- passport
        sections and enrolment only, never anything clinical from anywhere else your child is already connected.
      </p>

      {!isConfirmingRevoke ? (
        <button
          type="button"
          onClick={() => setIsConfirmingRevoke(true)}
          className="mt-3 block w-full lg:inline-block lg:w-auto rounded-xl border border-brand-golden-brown px-4 py-2 text-center text-xs font-semibold text-brand-golden-brown"
        >
          Revoke
        </button>
      ) : (
        <div className="mt-3 rounded-xl border border-brand-golden-brown/40 bg-white p-3">
          <p className="text-xs text-brand-neutral-black/70">Revoke this code? Nobody will be able to use it.</p>
          <div className="mt-2 flex gap-2">
            <button
              type="button"
              onClick={handleRevoke}
              disabled={isRevoking}
              className="rounded-lg bg-brand-golden-brown px-3 py-1.5 text-xs font-bold text-white disabled:opacity-50"
            >
              {isRevoking ? "Revoking…" : "Yes, revoke"}
            </button>
            <button
              type="button"
              onClick={() => setIsConfirmingRevoke(false)}
              className="rounded-lg border border-black/10 px-3 py-1.5 text-xs font-semibold text-brand-neutral-black/60"
            >
              Keep it
            </button>
          </div>
          {revokeError && (
            <p role="alert" className="mt-2 text-xs font-medium text-brand-golden-brown">
              {revokeError}
            </p>
          )}
        </div>
      )}
    </div>
  );
}
