/* Run this in the Supabase Dashboard: SQL Editor -> New query -> paste -> Run.

   passport_access.access_code was part of the original single-code
   design ("a 6-character alphanumeric code generated by parent"), from
   before the two-factor system existed. It's `not null` with no default,
   so every real Add Child insert under the new design -- which never
   sets it, since passports.passport_code + passport_institution_links
   now carry that role -- fails with "null value in column access_code
   violates not-null constraint". Confirmed live via a real teacher
   session completing every other check successfully and failing only
   on this. Nothing in the app references this column any more, so it's
   dropped outright rather than just relaxed to nullable. */

alter table public.passport_access
  drop column if exists access_code;
